//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SOVELAVIDBEntities : DbContext
    {
        public SOVELAVIDBEntities()
            : base("name=SOVELAVIDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_DONNEE> tbl_DONNEE { get; set; }
        public virtual DbSet<tbl_EVENEMENT> tbl_EVENEMENT { get; set; }
        public virtual DbSet<tbl_FIABILITE_SOURCE> tbl_FIABILITE_SOURCE { get; set; }
        public virtual DbSet<tbl_LAYER> tbl_LAYER { get; set; }
        public virtual DbSet<tbl_LAYER_CATEGORY> tbl_LAYER_CATEGORY { get; set; }
        public virtual DbSet<tbl_LAYER_TYPE> tbl_LAYER_TYPE { get; set; }
        public virtual DbSet<tbl_MENACE> tbl_MENACE { get; set; }
        public virtual DbSet<tbl_POI> tbl_POI { get; set; }
        public virtual DbSet<tbl_POI_TYPE> tbl_POI_TYPE { get; set; }
        public virtual DbSet<tbl_PRIORITE_EVENEMENT> tbl_PRIORITE_EVENEMENT { get; set; }
        public virtual DbSet<tbl_TYPE_EVENEMENT> tbl_TYPE_EVENEMENT { get; set; }
        public virtual DbSet<tbl_TYPE_MENACE> tbl_TYPE_MENACE { get; set; }
    }
}
