//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_POI
    {
        public int id { get; set; }
        public string nom { get; set; }
        public int poiType { get; set; }
        public string addresse { get; set; }
        public int communeId { get; set; }
        public bool isVulnerable { get; set; }
        public double lattitude { get; set; }
        public double longitude { get; set; }
    
        public virtual tbl_POI_TYPE tbl_POI_TYPE { get; set; }
    }
}
