//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LAYER
    {
        public int id { get; set; }
        public string fileName { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public System.DateTime dateAdded { get; set; }
        public int categoryId { get; set; }
        public int layerTypeId { get; set; }
        public System.DateTime validFrom { get; set; }
        public System.DateTime validTo { get; set; }
        public string imageName { get; set; }
    
        public virtual tbl_LAYER_CATEGORY tbl_LAYER_CATEGORY { get; set; }
        public virtual tbl_LAYER_TYPE tbl_LAYER_TYPE { get; set; }
    }
}
