//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DONNEE
    {
        public int id { get; set; }
        public string info { get; set; }
        public System.DateTime createdDate { get; set; }
        public int createdBy { get; set; }
        public int fiabiliteSource { get; set; }
        public string titre { get; set; }
    
        public virtual tbl_FIABILITE_SOURCE tbl_FIABILITE_SOURCE { get; set; }
    }
}
