//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MENACE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_MENACE()
        {
            this.tbl_EVENEMENT = new HashSet<tbl_EVENEMENT>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public int typeMenaceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_EVENEMENT> tbl_EVENEMENT { get; set; }
        public virtual tbl_TYPE_MENACE tbl_TYPE_MENACE { get; set; }
    }
}
